name: CI

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          run_install: true

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: lts/*

      - run: pnpm install

      - name: Lint code with ESLint
        run: pnpm lint
